# Generated by Django 4.2.1 on 2023-05-20 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='rollNumber',
            new_name='userId',
        ),
    ]
