# Generated by Django 4.2.1 on 2023-05-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_assistance_delete_prescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistance',
            old_name='AssistanceText',
            new_name='assistanceText',
        ),
    ]
